---
name: Setup
description: Installs tools and dependencies

runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      id: asdf-cache
      with:
        path: ~/.asdf
        key: asdf-${{ hashFiles('.tool-versions') }}
    - uses: asdf-vm/actions/install@v3
      if: '!steps.asdf-cache.outputs.cache-hit'
    - uses: mbta/actions/reshim-asdf@v2
    - uses: actions/cache@v3
      id: venv-cache
      with:
        path: ~/.cache/pypoetry
        key: venv-${{ hashFiles('poetry.lock') }}
    - run: poetry install
      shell: bash
      if: '!steps.venv-cache.outputs.cache-hit'
