---
name: Setup
description: Installs tools and dependencies

runs:
  using: composite
  steps:
    - uses: asdf-vm/actions/setup@v4
    - uses: actions/cache@v5
      id: asdf-cache
      with:
        key: asdf-${{ hashFiles('.tool-versions') }}
        restore-keys: asdf-
        path: |
          ${{ env.ASDF_DIR }}/plugins
          ${{ env.ASDF_DIR }}/installs
    - uses: asdf-vm/actions/install@v4
      if: '!steps.asdf-cache.outputs.cache-hit'
    - run: asdf reshim
      shell: bash
    - uses: actions/cache@v5
      id: venv-cache
      with:
        path: ~/.cache/pypoetry
        key: venv-${{ hashFiles('poetry.lock') }}
    - run: poetry install
      shell: bash
      if: '!steps.venv-cache.outputs.cache-hit'
