---
name: CI

on:
  push:
    paths-ignore:
      - images/**
      - '*.md'
      - LICENSE

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  SUBLIME_BUILD: 4200

jobs:
  check:
    name: Gleam Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: asdf-vm/actions/install@v4
      - run: cd tests && gleam check
  format:
    name: YAML Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: asdf-vm/actions/install@v4
      - run: source scripts/yamlcheck
  review:
    name: Package Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: asdf-vm/actions/install@v4
      - run: source scripts/review
  syntax:
    # Reference:
    # https://github.com/sublimehq/Packages/blob/master/.github/workflows/ci.yml
    name: Syntax Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: >
          mkdir -p ~/.sublime
          && curl -L https://download.sublimetext.com/st_syntax_tests_build_${{ env.SUBLIME_BUILD }}_x64.tar.xz
          | tar Jvx -C ~/.sublime --strip-components 1
      - run: |-
          mkdir ~/.sublime/Data/Packages/Gleam
          mv package tests ~/.sublime/Data/Packages/Gleam/
          ~/.sublime/syntax_tests
          rm -r ~/.sublime/Data/Packages/Gleam
